declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  export type IconProps = SVGProps<SVGSVGElement>;
  export type IconNode = [element: string, attrs: Record<string, string>][];
  export type LucideIcon = FC<IconProps>;
  export const Camera: LucideIcon;
  export const Users: LucideIcon;
  export const Building2: LucideIcon;
  export const Heart: LucideIcon;
  export const FileText: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Calendar: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const Lock: LucideIcon;
  export const Home: LucideIcon;
  export const Save: LucideIcon;
  export const Star: LucideIcon;
  export const Plus: LucideIcon;
  export const MapPin: LucideIcon;
  export const Phone: LucideIcon;
  export const Mail: LucideIcon;
  export const Instagram: LucideIcon;
  export const Facebook: LucideIcon;
  export const Clock: LucideIcon;
  export const Trash2: LucideIcon;
  export const Ruler: LucideIcon;
  export const Settings: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const ToggleLeft: LucideIcon;
  export const ToggleRight: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Eye: LucideIcon;
  export const LogOut: LucideIcon;
  export const Tag: LucideIcon;
  export const Image: LucideIcon;
  export const Printer: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
}
